entity: Warehouse
key: WarehouseID
endpoint: default
records:
- WarehouseID: WHMISS
  ReceivingLocationID: MAIN
  ShippingLocationID: MAIN
  RMALocationID: MAIN
- WarehouseID: WHQC
  ReceivingLocationID: MAIN
  ShippingLocationID: MAIN
  RMALocationID: MAIN
- WarehouseID: WHBC
  ReceivingLocationID: MAIN
  ShippingLocationID: MAIN
  RMALocationID: MAIN
