entity: KitSpecification
key: [KitInventoryID, RevisionID]
detail_keys:
  StockComponents: StockInventoryID
records:
- KitInventoryID: FG-IMMUNE-DEFENSE-60C
  RevisionID: V1
  Description: ImmunoShield 60-count bottle (BOM-IMMUNE-DEF-01)
  Active: true
  StockComponents:
  - StockInventoryID: RAW-ECH-EXT4
    ComponentQty: 0.012
    UOM: KG
  - StockInventoryID: RAW-ELD-EXT10
    ComponentQty: 0.009
    UOM: KG
  - StockInventoryID: RAW-ASH-EXT5
    ComponentQty: 0.006
    UOM: KG
- KitInventoryID: FG-CARDIO-OMEGA-COQ10-60SG
  RevisionID: V1
  Description: CardioPure 60-count bottle (BOM-CARDIO-OM3-01)
  Active: true
  StockComponents:
  - StockInventoryID: RAW-OMEGA3-70
    ComponentQty: 0.060
    UOM: KG
  - StockInventoryID: RAW-COQ10-99
    ComponentQty: 0.006
    UOM: KG
  - StockInventoryID: RAW-ASTA-10
    ComponentQty: 0.001
    UOM: KG
